MetaDataFormat: "yaml"

ContentDir: "content/en-US"
PublishDir: "public/en-US"

LanguageCode: en-US
BaseURL: "https://www.fxsitecompat.com/en-US/"
Title: "Firefox Site Compatibility"
Copyright: "Kohei Yoshino and individual contributors."

Author:
    Name: "Kohei Yoshino"
    Email: "webmaster@fxsitecompat.com"

Params:
    BaseDir: "/en-US/"
    AlternateBaseDir: "/ja/"
    GoogleAnalyticsID: "UA-37352183-2"
    Locales:
         - Code: "en-US"
           Name: "English"
         - Code: "ja"
           Name: "Japanese"
    DateFormat:
        ISO8601: "2006-01-02T15:04:05-07:00"
        Localized: "January 2, 2006"

Taxonomies:
    category: "categories"
    version: "versions"
    status: "statuses"

Menu:
    Main:
        - Name: "Home"
          Weight: 0
          Identifier: "home"
          URL: "/"
        - Name: "Blog"
          Weight: 1
          Identifier: "blog"
          URL: "/blog/"
        - Name: "Documents"
          Weight: 2
          Identifier: "docs"
          URL: "/docs/"
        - Name: "About"
          Weight: 3
          Identifier: "about"
          URL: "/about/"
        - Name: "Contribute"
          Weight: 4
          Identifier: "contribute"
          URL: "/contribute/"
    External:
        - Name: "Twitter"
          Weight: 0
          Identifier: "twitter"
          URL: "https://twitter.com/FxSiteCompat"
        - Name: "Facebook"
          Weight: 1
          Identifier: "facebook"
          URL: "https://www.facebook.com/FxSiteCompat"
        - Name: "Google+"
          Weight: 2
          Identifier: "google-plus"
          URL: "https://plus.google.com/+FxSiteCompatibility"
        - Name: "Google Group"
          Weight: 3
          Identifier: "google-group"
          URL: "https://groups.google.com/forum/#!forum/fxsitecompat"
        - Name: "GitHub"
          Weight: 4
          Identifier: "github"
          URL: "https://github.com/fxsitecompat"
