MetaDataFormat: "yaml"
disableHugoGeneratorInject: true

ContentDir: "content/ja"
PublishDir: "public/ja"

LanguageCode: ja
BaseURL: "https://www.fxsitecompat.com/ja/"
Title: "Firefox サイト互換性情報"
Copyright: "Kohei Yoshino and individual contributors."

Params:
    Domain: "FxSiteCompat.com"
    Author:
        Name: "Kohei Yoshino"
        Email: "webmaster@fxsitecompat.com"
        GoogleUserName: "KoheiYoshino"
        TwitterUserName: "koyoskeh"
        FacebookID: "100003919776216"
        FacebookUserName: "kohei.yoshino.aqr"
    Publisher:
        Name: "Firefox サイト互換性ワーキンググループ"
        GoogleUserName: "FxSiteCompatibility"
        TwitterUserName: "FxSiteCompat"
        FacebookID: "633917723366737"
        FacebookUserName: "FxSiteCompat"
    BaseDir: "/ja/"
    AlternateBaseDir: "/en-CA/"
    AlternateLangCode: "en-CA"
    GoogleSiteSearchID: "006388931142546140887:uidl4-zslfu"
    GoogleSiteSearchLangCode: "ja"
    FacebookLangCode: "ja_JP"
    Locales:
         - Code: "en-CA"
           Name: "英語"
         - Code: "ja"
           Name: "日本語"
    DateFormat:
        ISO8601: "2006-01-02T15:04:05-07:00"
        Localized: "2006 年 1 月 2 日"

Taxonomies:
    category: "categories"
    version: "versions"
    status: "statuses"

menu:
    main:
        - Name: "ホーム"
          Weight: 0
          Identifier: "home"
          URL: "/"
        - Name: "ブログ"
          Weight: 1
          Identifier: "blog"
          URL: "/blog/"
        - Name: "ドキュメント"
          Weight: 2
          Identifier: "docs"
          URL: "/docs/"
        - Name: "概要"
          Weight: 3
          Identifier: "about"
          URL: "/about/"
        - Name: "協力"
          Weight: 4
          Identifier: "contribute"
          URL: "/contribute/"
    external:
        - Name: "フィード"
          Weight: 0
          Identifier: "feed"
          URL: "/index.xml"
        - Name: "Twitter"
          Weight: 1
          Identifier: "twitter"
          URL: "https://twitter.com/FxSiteCompat"
        - Name: "Facebook"
          Weight: 2
          Identifier: "facebook"
          URL: "https://www.facebook.com/FxSiteCompat"
        - Name: "Google+"
          Weight: 3
          Identifier: "google-plus"
          URL: "https://plus.google.com/+FxSiteCompatibility"
        - Name: "GitHub"
          Weight: 4
          Identifier: "github"
          URL: "https://github.com/fxsitecompat"
